# Generated by Django 3.1.5 on 2021-02-06 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'message')},
        ),
    ]
